export const LOGIN_DIALOG_VISIBLE_OPEN = 'LOGIN_DIALOG_VISIBLE_OPEN';
export const LOGIN_DIALOG_VISIBLE_CLOSE = 'LOGIN_DIALOG_VISIBLE_CLOSE';
export const REGISTER_DIALOG_VISIBLE_OPEN = 'REGISTER_DIALOG_VISIBLE_OPEN';
export const REGISTER_DIALOG_VISIBLE_CLOSE = 'REGISTER_DIALOG_VISIBLE_CLOSE';
